### ISSUE TITLE
大佬 打包出来的jar包报错

### ISSUE THREAD

**Issue by azhibing** [pmiaowu/BurpShiroPassiveScan#13]
java.lang.NullPointerException
	at burp.an2.d(Unknown Source)
	at burp.bym.getHttpService(Unknown Source)
	at burp.cvu.getHttpService(Unknown Source)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:149)
	at burp.do7.b(Unknown Source)
	at burp.ph.a(Unknown Source)
	at burp.ph.a(Unknown Source)
	at burp.baa.a(Unknown Source)
	at burp.gvc.b(Unknown Source)
	at burp.ph.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addImpl(Container.java:1146)
	at java.desktop/javax.swing.JTabbedPane.insertTab(JTabbedPane.java:754)
	at burp.pw.a(Unknown Source)
	at burp.pw.insertTab(Unknown Source)
	at java.desktop/javax.swing.JTabbedPane.addTab(JTabbedPane.java:828)
	at burp.hrp.a(Unknown Source)
	at burp.baa.a(Unknown Source)
	at burp.baa.c(Unknown Source)
	at burp.gs6.a(Unknown Source)
	at burp.d82.addSuiteTab(Unknown Source)
	at burp.cq.addSuiteTab(Unknown Source)
	at burp.ekl.addSuiteTab(Unknown Source)
	at burp.Tags$1.run(Tags.java:75)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.NullPointerException
	at burp.an2.d(Unknown Source)
	at burp.bym.getHttpService(Unknown Source)
	at burp.cvu.getHttpService(Unknown Source)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:149)
	at burp.do7.b(Unknown Source)
	at burp.ph.a(Unknown Source)
	at burp.ph.a(Unknown Source)
	at burp.baa.a(Unknown Source)
	at burp.gvc.b(Unknown Source)
	at burp.ph.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addImpl(Container.java:1146)
	at java.desktop/javax.swing.JTabbedPane.insertTab(JTabbedPane.java:754)
	at burp.pw.a(Unknown Source)
	at burp.pw.insertTab(Unknown Source)
	at java.desktop/javax.swing.JTabbedPane.addTab(JTabbedPane.java:828)
	at burp.hrp.a(Unknown Source)
	at burp.baa.a(Unknown Source)
	at burp.baa.c(Unknown Source)
	at burp.gs6.a(Unknown Source)
	at burp.d82.addSuiteTab(Unknown Source)
	at burp.cq.addSuiteTab(Unknown Source)
	at burp.ekl.addSuiteTab(Unknown Source)
	at burp.Tags$1.run(Tags.java:75)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by azhibing** [comment]
解决了 电脑问题
