### ISSUE TITLE
加载之后报错

### ISSUE THREAD

**Issue by ThestaRY7** [pmiaowu/BurpShiroPassiveScan#15]
java.lang.NullPointerException: Cannot invoke "burp.IHttpRequestResponse.getHttpService()" because "this.currentlyDisplayedItem" is null
	at burp.e4j.M(Unknown Source)
	at burp.bs8.getHttpService(Unknown Source)
	at burp.bhw.getHttpService(Unknown Source)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:128)
	at burp.imm.a(Unknown Source)
	at burp.e_3.a(Unknown Source)
	at burp.e_3.a(Unknown Source)
	at burp.et9.a(Unknown Source)
	at burp.h96.b(Unknown Source)
	at burp.e_3.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addImpl(Container.java:1146)
	at java.desktop/javax.swing.JSplitPane.addImpl(JSplitPane.java:1009)
	at java.desktop/java.awt.Container.add(Container.java:997)
	at java.desktop/javax.swing.JSplitPane.setLeftComponent(JSplitPane.java:453)
	at burp.e_t.d(Unknown Source)
	at burp.e_t.c(Unknown Source)
	at burp.e_t.a(Unknown Source)
	at burp.e_t.lambda$layoutInitialised$2(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.NullPointerException: Cannot invoke "burp.IHttpRequestResponse.getHttpService()" because "this.currentlyDisplayedItem" is null
	at burp.e4j.M(Unknown Source)
	at burp.bs8.getHttpService(Unknown Source)
	at burp.bhw.getHttpService(Unknown Source)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:128)
	at burp.imm.a(Unknown Source)
	at burp.e_3.a(Unknown Source)
	at burp.e_3.a(Unknown Source)
	at burp.et9.a(Unknown Source)
	at burp.h96.b(Unknown Source)
	at burp.e_3.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addImpl(Container.java:1146)
	at java.desktop/javax.swing.JSplitPane.addImpl(JSplitPane.java:1009)
	at java.desktop/java.awt.Container.add(Container.java:997)
	at java.desktop/javax.swing.JSplitPane.setLeftComponent(JSplitPane.java:453)
	at burp.e_t.d(Unknown Source)
	at burp.e_t.c(Unknown Source)
	at burp.e_t.a(Unknown Source)
	at burp.e_t.lambda$layoutInitialised$2(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

![image](https://user-images.githubusercontent.com/48352738/142990405-0e25923c-9e15-419f-a22e-37501e099345.png)

**Comment by ThestaRY7** [comment]
burpsuite pro v2021.6.1

**Comment by history3** [comment]
同样报错 大佬在哪
========插件错误-未知错误============
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at burp.Application.CmdEchoExtension.CmdEcho.init(CmdEcho.java:56)
	at burp.Application.CmdEchoExtension.CmdEcho.<init>(CmdEcho.java:35)
	at burp.BurpExtender.cmdEchoExtension(BurpExtender.java:274)
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:174)
	at burp.f5p.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Response cannot be null
	at burp.c6r.analyzeResponse(Unknown Source)
	at burp.e3m.analyzeResponse(Unknown Source)
	at burp.Application.CmdEchoExtension.ExtensionMethod.CmdEchoScan.cmdEchoDetection(CmdEchoScan.java:96)
	at burp.Application.CmdEchoExtension.ExtensionMethod.CmdEchoScan.runExtension(CmdEchoScan.java:73)
	at burp.Application.CmdEchoExtension.ExtensionMethod.CmdEchoScan.<init>(CmdEchoScan.java:55)
	... 14 more
java.lang.NullPointerException: Response cannot be null
	at burp.c6r.analyzeResponse(Unknown Source)
	at burp.e3m.analyzeResponse(Unknown Source)
	at burp.Application.CmdEchoExtension.ExtensionMethod.CmdEchoScan.cmdEchoDetection(CmdEchoScan.java:96)
	at burp.Application.CmdEchoExtension.ExtensionMethod.CmdEchoScan.runExtension(CmdEchoScan.java:73)
	at burp.Application.CmdEchoExtension.ExtensionMethod.CmdEchoScan.<init>(CmdEchoScan.java:55)
	at sun.reflect.GeneratedConstructorAccessor61.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at burp.Application.CmdEchoExtension.CmdEcho.init(CmdEcho.java:56)
	at burp.Application.CmdEchoExtension.CmdEcho.<init>(CmdEcho.java:35)
	at burp.BurpExtender.cmdEchoExtension(BurpExtender.java:274)
	at burp.BurpExtender.doPassiveScan(BurpExtender.java:174)
	at burp.f5p.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
