### ISSUE TITLE
使用jdk11 编译仍然报错

### ISSUE THREAD

**Issue by Pa55w0rd** [pmiaowu/BurpShiroPassiveScan#20]
java.lang.NullPointerException
	at burp.e4t.Z(Unknown Source)
	at burp.g0_.getHttpService(Unknown Source)
	at burp.fp8.getHttpService(Unknown Source)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:346)
	at burp.fb0.a(Unknown Source)
	at burp.gbo.b(Unknown Source)
	at burp.i9u.a(Unknown Source)
	at burp.i9u.a(Unknown Source)
	at burp.cju.a(Unknown Source)
	at burp.c_m.b(Unknown Source)
	at burp.h1z.b(Unknown Source)
	at burp.cju.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addImpl(Container.java:1146)
	at java.desktop/javax.swing.JTabbedPane.insertTab(JTabbedPane.java:730)
	at burp.azq.a(Unknown Source)
	at burp.azq.insertTab(Unknown Source)
	at java.desktop/javax.swing.JTabbedPane.addTab(JTabbedPane.java:804)
	at burp.fa0.a(Unknown Source)
	at burp.c_m.b(Unknown Source)
	at burp.c_m.a(Unknown Source)
	at burp.hmq.a(Unknown Source)
	at burp.h6d.addSuiteTab(Unknown Source)
	at burp.hs7.addSuiteTab(Unknown Source)
	at burp.em9.addSuiteTab(Unknown Source)
	at burp.Tags$1.run(Tags.java:75)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.NullPointerException
	at burp.e4t.Z(Unknown Source)
	at burp.g0_.getHttpService(Unknown Source)
	at burp.fp8.getHttpService(Unknown Source)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:346)
	at burp.fb0.a(Unknown Source)
	at burp.gbo.b(Unknown Source)
	at burp.i9u.a(Unknown Source)
	at burp.i9u.a(Unknown Source)
	at burp.cju.a(Unknown Source)
	at burp.c_m.b(Unknown Source)
	at burp.h1z.b(Unknown Source)
	at burp.cju.addNotify(Unknown Source)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addNotify(Container.java:2800)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4783)
	at java.desktop/java.awt.Container.addImpl(Container.java:1146)
	at java.desktop/javax.swing.JTabbedPane.insertTab(JTabbedPane.java:730)
	at burp.azq.a(Unknown Source)
	at burp.azq.insertTab(Unknown Source)
	at java.desktop/javax.swing.JTabbedPane.addTab(JTabbedPane.java:804)
	at burp.fa0.a(Unknown Source)
	at burp.c_m.b(Unknown Source)
	at burp.c_m.a(Unknown Source)
	at burp.hmq.a(Unknown Source)
	at burp.h6d.addSuiteTab(Unknown Source)
	at burp.hs7.addSuiteTab(Unknown Source)
	at burp.em9.addSuiteTab(Unknown Source)
	at burp.Tags$1.run(Tags.java:75)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by pmiaowu** [comment]
推断你使用了HaE
建议你升级HaE: https://github.com/gh0stkey/HaE
HaE2.1.3这个版本以后不会在影响其它插件了
