### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by XIAOchengqingjun** [pmiaowu/BurpShiroPassiveScan#36]
### java.lang.NoClassDefFoundError: org/yaml/snakeyaml/Yaml
	at burp.Bootstrap.YamlReader.<init>(YamlReader.java:25)
	at burp.Bootstrap.YamlReader.getInstance(YamlReader.java:31)
	at burp.Ui.Tags.<init>(Tags.java:24)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:55)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at burp.hms.lambda$registerExtenderCallbacks$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.ClassNotFoundException: org.yaml.snakeyaml.Yaml
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 12 more
###

**Comment by payprays** [comment]
try to add the file, ./resources/config.yml  in your jar file extensions folder.
直接找它的发行[jar](https://github.com/pmiaowu/BurpShiroPassiveScan/releases)导入，然后在jar文件所在的文件夹下添加这个文件./resources/config.yml，我是这么解决的。

**Comment by gggao12** [comment]
./resources/config.yml这个文件里面写什么师傅

**Comment by payprays** [comment]
默认的就好了
