### ISSUE TITLE
burp加载插件时候报空指针错误

### ISSUE THREAD

**Issue by nibiwodong** [pmiaowu/BurpShiroPassiveScan#5]
如题：
`java.lang.NullPointerException
	at burp.f1k.b(Unknown Source)
	at burp.g72.getHttpService(Unknown Source)
	at burp.d9x.getHttpService(Unknown Source)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:346)
	at burp.fjg.a(Unknown Source)
	at burp.dn5.a(Unknown Source)
	at burp.dn5.a(Unknown Source)
	at burp.gcg.b(Unknown Source)
	at burp.f47.b(Unknown Source)
	at burp.dn5.addNotify(Unknown Source)
	at java.awt.Container.addNotify(Container.java:2776)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2776)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2776)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addImpl(Container.java:1124)
	at javax.swing.JTabbedPane.insertTab(JTabbedPane.java:724)
	at burp.dny.a(Unknown Source)
	at burp.dny.insertTab(Unknown Source)
	at javax.swing.JTabbedPane.addTab(JTabbedPane.java:798)
	at burp.a3o.a(Unknown Source)
	at burp.gcg.c(Unknown Source)
	at burp.gcg.b(Unknown Source)
	at burp.a3z.a(Unknown Source)
	at burp.art.addSuiteTab(Unknown Source)
	at burp.fh8.addSuiteTab(Unknown Source)
	at burp.wv.addSuiteTab(Unknown Source)
	at burp.Tags$1.run(Tags.java:75)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.lang.NullPointerException
	at burp.f1k.b(Unknown Source)
	at burp.g72.getHttpService(Unknown Source)
	at burp.d9x.getHttpService(Unknown Source)
	at burp.BurpExtender$MarkInfoTab.isEnabled(BurpExtender.java:346)
	at burp.fjg.a(Unknown Source)
	at burp.dn5.a(Unknown Source)
	at burp.dn5.a(Unknown Source)
	at burp.gcg.b(Unknown Source)
	at burp.f47.b(Unknown Source)
	at burp.dn5.addNotify(Unknown Source)
	at java.awt.Container.addNotify(Container.java:2776)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2776)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addNotify(Container.java:2776)
	at javax.swing.JComponent.addNotify(JComponent.java:4740)
	at java.awt.Container.addImpl(Container.java:1124)
	at javax.swing.JTabbedPane.insertTab(JTabbedPane.java:724)
	at burp.dny.a(Unknown Source)
	at burp.dny.insertTab(Unknown Source)
	at javax.swing.JTabbedPane.addTab(JTabbedPane.java:798)
	at burp.a3o.a(Unknown Source)
	at burp.gcg.c(Unknown Source)
	at burp.gcg.b(Unknown Source)
	at burp.a3z.a(Unknown Source)
	at burp.art.addSuiteTab(Unknown Source)
	at burp.fh8.addSuiteTab(Unknown Source)
	at burp.wv.addSuiteTab(Unknown Source)
	at burp.Tags$1.run(Tags.java:75)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by pmiaowu** [comment]
实在没遇到过这种情况。。你的burp版本是？

**Comment by pmiaowu** [comment]
实在没遇到过这种情况。。你的burp版本是？

**Comment by nibiwodong** [comment]
2.0.11beta版本

**Comment by HongLuDianXue** [comment]
报错+1
